IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[tblCancion]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[tblCancion](
		IdCancion BIGINT IDENTITY(1,1) NOT NULL,
		IdArtista BIGINT NOT NULL,
		Nombre VARCHAR(150) NOT NULL,
		Duracion VARCHAR(20) NOT NULL,
	 CONSTRAINT [PK_tblCancion] PRIMARY KEY CLUSTERED 
	(
		[IdCancion] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [dbo].[tblCancion]  WITH CHECK ADD CONSTRAINT [FK_tblCancion_tblArtista] FOREIGN KEY([IdArtista]) REFERENCES [dbo].[tblArtista] ([IdArtista])
END